project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "Bethany Williams"
  repo-url: https://github.com/bethany-williams/bethany-williams.github.io
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: Publications.qmd
      - text: "Projects"
        href: Projects.qmd
    right: 
      - icon: github
        href: https://github.com/bethany-williams/bethany-williams.github.io
  page-footer: 
    center: "Copyright 2025, Bethany Williams"
    background: secondary
    border: false


fig-dpi: 600 # Figure resolution 
format:
  html:
    toc: true
    toc_float: true
    toc-depth: 2
    page-layout: full
    link-external-newwindow: true
    link-external-icon: false
    theme:
      light: theme_light.scss
      dark: theme_dark.scss
    mainfont: Open Sans
    grid:
      margin-width: 150px 
      sidebar-width: 0px
      body-width: 1000px
repo-actions: false